services:
  s3admin:
    image: dpage/pgadmin4
    container_name: 68-s3-admin
    environment:
      PGADMIN_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_PASSWORD: ${PGADMIN_PASSWORD}
    env_file:
      - .env
    ports:
      - "2345:80"